version: '3.6'
services:
  php:
    # image: 'php:7.3-fpm'
    build:
        context: ./docker
        dockerfile: php.Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
        - './html:/var/www/html'
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php'
    volumes:
      - ./nginx/default.conf:/tmp/default.template
      - ./html:/var/www/html:rw,cached
      - ./certs:/etc/certs
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'

  mysql:
    image: mariadb
    container_name: ${APP_NAME}-mysql
    volumes:
       - './data/db:/var/lib/mysql:delegated'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmins
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - '8080:80'
    links:
      - mysql:mysql

